version: "3.7"
services:

  dev:
    build: 
      context: .
      target: dev
    image: dev_image
    volumes:
      - .:/home/root/.
    command: bash -c "poetry run python"
    tty: true

  prod:
    build: 
      context: .
      target: prod
    image: prod_image
    command: /bin/bash
    tty: true
